// Auto-generated by `fea-docs init` — review before using.
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '.');

/** @type {import('fea-docs').FeaDocsConfig} */
export default {
  frameworks: ['react'],
  aliases: {
    '@fea-lib/values': path.join(root, 'libs/fea-lib/values/src/index.ts'),
    '@fea-lib/jscad': path.join(root, 'libs/fea-lib/jscad/src/index.ts'),
    '@components': path.join(root, 'components'),
    '@docs': path.join(root, 'docs'),
  },
  dependencies: {
    '@codesandbox/sandpack-react': '^2.20.0',
    'three': '^0.182.0',
  },
};
